name: deploy-to-server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ytsm-test-1
    steps:
      - name: clone repository
        run: |
          cd /root/devops
          sudo rm -rf ${{ github.event.repository.name }}
          sudo git clone --branch dev https://${{ secrets.TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.event.repository.name }}.git

      - name: docker build & run
        run: |
          cd /root/devops
          sudo docker compose up -d --build --force-recreate

      - name: list running docker containers
        run: |
          sudo docker ps
